// Agent registry — sourced from Puppeteer PRD §8 Agent Library Specification.
export type AgentKind = 'tool' | 'reasoning' | 'terminal'

export interface AgentSpec {
  id: string
  name: string
  kind: AgentKind
  short: string         // 4-8 char glyph for nodes
  pattern: string       // reasoning pattern
  tools: string[]
  maxTokens: number
  timeoutMs: number
  costWeight: number
  blurb: string
  // Heuristic affinities for the simulated policy
  affinities: { math?: number; web?: number; code?: number; research?: number; critique?: number; synth?: number; plan?: number }
}

export const AGENTS: AgentSpec[] = [
  {
    id: 'planner',
    name: 'PlannerAgent',
    kind: 'reasoning',
    short: 'PLN',
    pattern: 'Chain-of-Thought',
    tools: [],
    maxTokens: 2000,
    timeoutMs: 8000,
    costWeight: 4,
    blurb: 'Decomposes the task into ordered sub-steps and emits a structured plan.',
    affinities: { plan: 1.0 },
  },
  {
    id: 'critic',
    name: 'CriticAgent',
    kind: 'reasoning',
    short: 'CRT',
    pattern: 'Socratic',
    tools: [],
    maxTokens: 2000,
    timeoutMs: 8000,
    costWeight: 4,
    blurb: 'Reviews prior output for hallucinations, logical gaps and unsupported claims.',
    affinities: { critique: 1.0 },
  },
  {
    id: 'reflect',
    name: 'ReflectAgent',
    kind: 'reasoning',
    short: 'RFL',
    pattern: 'Reflexion',
    tools: [],
    maxTokens: 2000,
    timeoutMs: 8000,
    costWeight: 5,
    blurb: 'Analyzes the trajectory so far and proposes the next best action.',
    affinities: { critique: 0.6, plan: 0.4 },
  },
  {
    id: 'modifier',
    name: 'ModifierAgent',
    kind: 'reasoning',
    short: 'MOD',
    pattern: 'Edit-then-Critique',
    tools: [],
    maxTokens: 4000,
    timeoutMs: 12000,
    costWeight: 5,
    blurb: 'Takes prior output plus a critique and produces a revised, corrected version.',
    affinities: { critique: 0.7, synth: 0.4 },
  },
  {
    id: 'concluder',
    name: 'ConcluderAgent',
    kind: 'reasoning',
    short: 'CNC',
    pattern: 'Synthesis',
    tools: [],
    maxTokens: 6000,
    timeoutMs: 14000,
    costWeight: 6,
    blurb: 'Aggregates all prior agent outputs into a final coherent response.',
    affinities: { synth: 1.0 },
  },
  {
    id: 'bing',
    name: 'BingAgent',
    kind: 'tool',
    short: 'BNG',
    pattern: 'Tool Use',
    tools: ['DuckDuckGo Search'],
    maxTokens: 2000,
    timeoutMs: 15000,
    costWeight: 3,
    blurb: 'Web search with DuckDuckGo, free and fast results without API keys.',
    affinities: { web: 1.0, research: 0.7 },
  },
  {
    id: 'arxiv',
    name: 'ArxivAgent',
    kind: 'tool',
    short: 'ARX',
    pattern: 'Tool Use',
    tools: ['arXiv API'],
    maxTokens: 3000,
    timeoutMs: 20000,
    costWeight: 3,
    blurb: 'Retrieves and summarises peer-reviewed and pre-print research.',
    affinities: { research: 1.0 },
  },
  {
    id: 'python',
    name: 'PythonAgent',
    kind: 'tool',
    short: 'PY',
    pattern: 'Tool Use',
    tools: ['Python 3.11 (local)'],
    maxTokens: 4000,
    timeoutMs: 30000,
    costWeight: 5,
    blurb: 'Sandboxed execution for math, data work and verification scripts.',
    affinities: { code: 1.0, math: 0.9 },
  },
  {
    id: 'browser',
    name: 'BrowserAgent',
    kind: 'tool',
    short: 'BRW',
    pattern: 'Tool Use',
    tools: ['Headless Chromium'],
    maxTokens: 4000,
    timeoutMs: 45000,
    costWeight: 7,
    blurb: 'Headless browser session with allow-listed domains, no credential access.',
    affinities: { web: 0.7, research: 0.5 },
  },
  {
    id: 'data',
    name: 'DataAgent',
    kind: 'tool',
    short: 'DAT',
    pattern: 'Tool Use',
    tools: ['Pandas', 'SQLite'],
    maxTokens: 3000,
    timeoutMs: 30000,
    costWeight: 4,
    blurb: 'Tabular analysis, joins and aggregation over user-supplied data frames.',
    affinities: { code: 0.6, math: 0.6 },
  },
  {
    id: 'wolfram',
    name: 'WolframAgent',
    kind: 'tool',
    short: 'WLF',
    pattern: 'Tool Use',
    tools: ['Wolfram Alpha API'],
    maxTokens: 1000,
    timeoutMs: 10000,
    costWeight: 4,
    blurb: 'Symbolic and numeric computation backed by Wolfram knowledge.',
    affinities: { math: 1.0 },
  },
  {
    id: 'hn',
    name: 'HackerNewsAgent',
    kind: 'tool',
    short: 'HN',
    pattern: 'Tool Use',
    tools: ['HN Algolia API'],
    maxTokens: 2000,
    timeoutMs: 12000,
    costWeight: 3,
    blurb: 'Pulls recent Hacker News stories — strong signal for developer trends and launches.',
    affinities: { web: 0.8, research: 0.6 },
  },
  {
    id: 'coder',
    name: 'CoderAgent',
    kind: 'reasoning',
    short: 'COD',
    pattern: 'Code Synthesis',
    tools: [],
    maxTokens: 4000,
    timeoutMs: 14000,
    costWeight: 5,
    blurb: 'Designs and writes production-quality code with tradeoffs, separate from execution.',
    affinities: { code: 1.0, plan: 0.4 },
  },
  {
    id: 'verifier',
    name: 'VerifierAgent',
    kind: 'reasoning',
    short: 'VFY',
    pattern: 'Claim Grounding',
    tools: [],
    maxTokens: 3000,
    timeoutMs: 14000,
    costWeight: 5,
    blurb: 'Final ground-check pass: extracts claims from the draft and rates each against retrieved sources.',
    affinities: { critique: 1.0, research: 0.5 },
  },
  {
    id: 'terminator',
    name: 'Terminator',
    kind: 'terminal',
    short: 'END',
    pattern: '—',
    tools: [],
    maxTokens: 0,
    timeoutMs: 0,
    costWeight: 0,
    blurb: 'Signals task completion. Orchestrator halts execution when chosen.',
    affinities: {},
  },
]

export const AGENT_BY_ID = Object.fromEntries(AGENTS.map(a => [a.id, a])) as Record<string, AgentSpec>
